package com.biosimilarity.lift.lib.json.Absyn; // Java Package generated by the BNF Converter.

public class JInt extends JSONInt {
  public final Integer integer_;

  public JInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.json.Absyn.JSONInt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.json.Absyn.JInt) {
      com.biosimilarity.lift.lib.json.Absyn.JInt x = (com.biosimilarity.lift.lib.json.Absyn.JInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
