package com.biosimilarity.lift.lib.json.Absyn; // Java Package generated by the BNF Converter.

public class JNul extends JSONValue {

  public JNul() { }

  public <R,A> R accept(com.biosimilarity.lift.lib.json.Absyn.JSONValue.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.json.Absyn.JNul) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
