package com.biosimilarity.magritte.json.Absyn; // Java Package generated by the BNF Converter.

public class JPair extends JSONPair {
  public final String string_;
  public final JSONValue jsonvalue_;

  public JPair(String p1, JSONValue p2) { string_ = p1; jsonvalue_ = p2; }

  public <R,A> R accept(com.biosimilarity.magritte.json.Absyn.JSONPair.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.magritte.json.Absyn.JPair) {
      com.biosimilarity.magritte.json.Absyn.JPair x = (com.biosimilarity.magritte.json.Absyn.JPair)o;
      return this.string_.equals(x.string_) && this.jsonvalue_.equals(x.jsonvalue_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.string_.hashCode())+this.jsonvalue_.hashCode();
  }


}
