package com.biosimilarity.lift.lib.json.Absyn; // Java Package generated by the BNF Converter.

public abstract class JSONNum implements java.io.Serializable {
  public abstract <R,A> R accept(JSONNum.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.json.Absyn.JDbl p, A arg);

  }

}
