
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 19 22:19:27 PST 2012
//----------------------------------------------------

package com.biosimilarity.lift.model.specialK;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _INTEGER_ = 18;
  public static final int _STRING_ = 17;
  public static final int UIdent = 20;
  public static final int _DOUBLE_ = 19;
  public static final int _SYMB_14 = 16;
  public static final int _SYMB_13 = 15;
  public static final int _SYMB_12 = 14;
  public static final int _SYMB_9 = 11;
  public static final int _SYMB_11 = 13;
  public static final int _SYMB_10 = 12;
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int EOF = 0;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int Wild = 22;
  public static final int error = 1;
  public static final int LIdent = 21;
}

