package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class AtomPort extends Port {
  public final Integer integer_;

  public AtomPort(Integer p1) { integer_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.Port.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.AtomPort) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.AtomPort x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.AtomPort)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
