package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class BasicURI extends URI {
  public final URIScheme urischeme_;
  public final URIPath uripath_;

  public BasicURI(URIScheme p1, URIPath p2) { urischeme_ = p1; uripath_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.URI.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.BasicURI) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.BasicURI x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.BasicURI)o;
      return this.urischeme_.equals(x.urischeme_) && this.uripath_.equals(x.uripath_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.urischeme_.hashCode())+this.uripath_.hashCode();
  }


}
