package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBTellReq extends KVDBRequest {
  public final TellReq tellreq_;
  public final TellReqPacket tellreqpacket_;

  public KVDBTellReq(TellReq p1, TellReqPacket p2) { tellreq_ = p1; tellreqpacket_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBRequest.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBTellReq) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBTellReq x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBTellReq)o;
      return this.tellreq_.equals(x.tellreq_) && this.tellreqpacket_.equals(x.tellreqpacket_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.tellreq_.hashCode())+this.tellreqpacket_.hashCode();
  }


}
