package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBSubst extends Substitution {
  public final ListSubstPair listsubstpair_;

  public KVDBSubst(ListSubstPair p1) { listsubstpair_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.Substitution.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBSubst) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBSubst x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBSubst)o;
      return this.listsubstpair_.equals(x.listsubstpair_);
    }
    return false;
  }

  public int hashCode() {
    return this.listsubstpair_.hashCode();
  }


}
