package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBJustReqHB extends Message {
  public final LblReqHeader lblreqheader_;
  public final LblReqBody lblreqbody_;

  public KVDBJustReqHB(LblReqHeader p1, LblReqBody p2) { lblreqheader_ = p1; lblreqbody_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.Message.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBJustReqHB) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBJustReqHB x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBJustReqHB)o;
      return this.lblreqheader_.equals(x.lblreqheader_) && this.lblreqbody_.equals(x.lblreqbody_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.lblreqheader_.hashCode())+this.lblreqbody_.hashCode();
  }


}
