package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBAskRspData extends AskRspPacket {
  public final Pattern pattern_;
  public final Substitution substitution_;
  public final Blob blob_;

  public KVDBAskRspData(Pattern p1, Substitution p2, Blob p3) { pattern_ = p1; substitution_ = p2; blob_ = p3; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.AskRspPacket.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBAskRspData) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBAskRspData x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBAskRspData)o;
      return this.pattern_.equals(x.pattern_) && this.substitution_.equals(x.substitution_) && this.blob_.equals(x.blob_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.pattern_.hashCode())+this.substitution_.hashCode())+this.blob_.hashCode();
  }


}
