package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBPrimUUID extends UUID {
  public final String primuuid_;

  public KVDBPrimUUID(String p1) { primuuid_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.UUID.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBPrimUUID) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBPrimUUID x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBPrimUUID)o;
      return this.primuuid_.equals(x.primuuid_);
    }
    return false;
  }

  public int hashCode() {
    return this.primuuid_.hashCode();
  }


}
