package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBReqNoHdr extends ReqHeader {

  public KVDBReqNoHdr() { }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.ReqHeader.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBReqNoHdr) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
