package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBAskReqData extends AskReqPacket {
  public final Pattern pattern_;

  public KVDBAskReqData(Pattern p1) { pattern_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.AskReqPacket.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBAskReqData) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBAskReqData x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBAskReqData)o;
      return this.pattern_.equals(x.pattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.pattern_.hashCode();
  }


}
