package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class KVDBTellReqData extends TellReqPacket {
  public final Pattern pattern_;
  public final Blob blob_;

  public KVDBTellReqData(Pattern p1, Blob p2) { pattern_ = p1; blob_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.TellReqPacket.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBTellReqData) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBTellReqData x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBTellReqData)o;
      return this.pattern_.equals(x.pattern_) && this.blob_.equals(x.blob_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pattern_.hashCode())+this.blob_.hashCode();
  }


}
