package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class LocatedtedPath extends URIPath {
  public final URILocation urilocation_;
  public final URIRelativePath urirelativepath_;

  public LocatedtedPath(URILocation p1, URIRelativePath p2) { urilocation_ = p1; urirelativepath_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.URIPath.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.LocatedtedPath) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.LocatedtedPath x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.LocatedtedPath)o;
      return this.urilocation_.equals(x.urilocation_) && this.urirelativepath_.equals(x.urirelativepath_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.urilocation_.hashCode())+this.urirelativepath_.hashCode();
  }


}
