package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public class QBool extends QryGrndLit {
  public final QryBool qrybool_;

  public QBool(QryBool p1) { qrybool_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryGrndLit.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.kvdbJSON.Absyn.QBool) {
      com.biosimilarity.lift.lib.kvdbJSON.Absyn.QBool x = (com.biosimilarity.lift.lib.kvdbJSON.Absyn.QBool)o;
      return this.qrybool_.equals(x.qrybool_);
    }
    return false;
  }

  public int hashCode() {
    return this.qrybool_.hashCode();
  }


}
