package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public abstract class QryNum implements java.io.Serializable {
  public abstract <R,A> R accept(QryNum.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.kvdbJSON.Absyn.QInt p, A arg);
    public R visit(com.biosimilarity.lift.lib.kvdbJSON.Absyn.QDbl p, A arg);

  }

}
