package com.biosimilarity.lift.lib.kvdbJSON.Absyn; // Java Package generated by the BNF Converter.

public abstract class TellReq implements java.io.Serializable {
  public abstract <R,A> R accept(TellReq.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBPutReq p, A arg);
    public R visit(com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBStoreReq p, A arg);
    public R visit(com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBPublishReq p, A arg);

  }

}
