package com.biosimilarity.lift.model.specialK.Absyn; // Java Package generated by the BNF Converter.

public class Applicand extends Concretion {
  public final Information information_;
  public final Agent agent_;

  public Applicand(Information p1, Agent p2) { information_ = p1; agent_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.specialK.Absyn.Concretion.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.specialK.Absyn.Applicand) {
      com.biosimilarity.lift.model.specialK.Absyn.Applicand x = (com.biosimilarity.lift.model.specialK.Absyn.Applicand)o;
      return this.information_.equals(x.information_) && this.agent_.equals(x.agent_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.information_.hashCode())+this.agent_.hashCode();
  }


}
