package com.biosimilarity.lift.model.specialK.Absyn; // Java Package generated by the BNF Converter.

public class Atomic extends Variation {
  public final String uident_;

  public Atomic(String p1) { uident_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.specialK.Absyn.Variation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.specialK.Absyn.Atomic) {
      com.biosimilarity.lift.model.specialK.Absyn.Atomic x = (com.biosimilarity.lift.model.specialK.Absyn.Atomic)o;
      return this.uident_.equals(x.uident_);
    }
    return false;
  }

  public int hashCode() {
    return this.uident_.hashCode();
  }


}
