package com.biosimilarity.lift.model.specialK.Absyn; // Java Package generated by the BNF Converter.

public class DoubleLiteral extends Value {
  public final Double double_;

  public DoubleLiteral(Double p1) { double_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.specialK.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.specialK.Absyn.DoubleLiteral) {
      com.biosimilarity.lift.model.specialK.Absyn.DoubleLiteral x = (com.biosimilarity.lift.model.specialK.Absyn.DoubleLiteral)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
