package com.biosimilarity.lift.model.specialK.Absyn; // Java Package generated by the BNF Converter.

public abstract class Information implements java.io.Serializable {
  public abstract <R,A> R accept(Information.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.specialK.Absyn.Indirection p, A arg);
    public R visit(com.biosimilarity.lift.model.specialK.Absyn.Reflection p, A arg);

  }

}
