package com.biosimilarity.lift.model.specialK.Absyn; // Java Package generated by the BNF Converter.

public class Superposition extends Agent {
  public final ListGuardedAgent listguardedagent_;

  public Superposition(ListGuardedAgent p1) { listguardedagent_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.specialK.Absyn.Agent.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.specialK.Absyn.Superposition) {
      com.biosimilarity.lift.model.specialK.Absyn.Superposition x = (com.biosimilarity.lift.model.specialK.Absyn.Superposition)o;
      return this.listguardedagent_.equals(x.listguardedagent_);
    }
    return false;
  }

  public int hashCode() {
    return this.listguardedagent_.hashCode();
  }


}
