package com.biosimilarity.lift.model.specialK.Absyn; // Java Package generated by the BNF Converter.

public class Transcription extends Variation {
  public final Agent agent_;

  public Transcription(Agent p1) { agent_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.specialK.Absyn.Variation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.specialK.Absyn.Transcription) {
      com.biosimilarity.lift.model.specialK.Absyn.Transcription x = (com.biosimilarity.lift.model.specialK.Absyn.Transcription)o;
      return this.agent_.equals(x.agent_);
    }
    return false;
  }

  public int hashCode() {
    return this.agent_.hashCode();
  }


}
