package com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn; // Java Package generated by the BNF Converter.

public abstract class QryValue implements java.io.Serializable {
  public abstract <R,A> R accept(QryValue.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QAtomic p, A arg);
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QColl p, A arg);
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QComp p, A arg);

  }

}
