package com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn; // Java Package generated by the BNF Converter.

public class QVal extends QryElem {
  public final QryValue qryvalue_;

  public QVal(QryValue p1) { qryvalue_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryElem.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QVal) {
      com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QVal x = (com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QVal)o;
      return this.qryvalue_.equals(x.qryvalue_);
    }
    return false;
  }

  public int hashCode() {
    return this.qryvalue_.hashCode();
  }


}
