package com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn; // Java Package generated by the BNF Converter.

public abstract class ReqHeader implements java.io.Serializable {
  public abstract <R,A> R accept(ReqHeader.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.KVDBReqHdr p, A arg);
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.KVDBReqNoHdr p, A arg);
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.KVDBReqURIHdr p, A arg);
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.KVDBReqUUIDHdr p, A arg);

  }

}
