package com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn; // Java Package generated by the BNF Converter.

public abstract class URIRelativePath implements java.io.Serializable {
  public abstract <R,A> R accept(URIRelativePath.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.SlashPath p, A arg);

  }

}
