package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class CclV extends Value {
  public final ILLCode illcode_1, illcode_2;
  public final Env env_;

  public CclV(ILLCode p1, ILLCode p2, Env p3) { illcode_1 = p1; illcode_2 = p2; env_ = p3; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.CclV) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.CclV x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.CclV)o;
      return this.illcode_1.equals(x.illcode_1) && this.illcode_2.equals(x.illcode_2) && this.env_.equals(x.env_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.illcode_1.hashCode())+this.illcode_2.hashCode())+this.env_.hashCode();
  }


}
