package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public abstract class Dump implements java.io.Serializable {
  public abstract <R,A> R accept(Dump.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.MDUMP p, A arg);

  }

}
