package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class ENVIRONMENT extends Env {
  public final ListValue listvalue_;

  public ENVIRONMENT(ListValue p1) { listvalue_ = p1; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Env.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.ENVIRONMENT) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.ENVIRONMENT x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.ENVIRONMENT)o;
      return this.listvalue_.equals(x.listvalue_);
    }
    return false;
  }

  public int hashCode() {
    return this.listvalue_.hashCode();
  }


}
