package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public abstract class Frame implements java.io.Serializable {
  public abstract <R,A> R accept(Frame.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.STACKFRAME p, A arg);

  }

}
