package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class HEAD extends Instruction {
  public final String illhd_;

  public HEAD(String p1) { illhd_ = p1; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Instruction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.HEAD) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.HEAD x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.HEAD)o;
      return this.illhd_.equals(x.illhd_);
    }
    return false;
  }

  public int hashCode() {
    return this.illhd_.hashCode();
  }


}
