package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public abstract class ILLCode implements java.io.Serializable {
  public abstract <R,A> R accept(ILLCode.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.CODESEQ p, A arg);

  }

}
