package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class MSTACK extends Stack {
  public final ListEnvOrVal listenvorval_;

  public MSTACK(ListEnvOrVal p1) { listenvorval_ = p1; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Stack.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.MSTACK) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.MSTACK x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.MSTACK)o;
      return this.listenvorval_.equals(x.listenvorval_);
    }
    return false;
  }

  public int hashCode() {
    return this.listenvorval_.hashCode();
  }


}
