package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class PairV extends Value {
  public final Value value_1, value_2;

  public PairV(Value p1, Value p2) { value_1 = p1; value_2 = p2; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.PairV) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.PairV x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.PairV)o;
      return this.value_1.equals(x.value_1) && this.value_2.equals(x.value_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.value_1.hashCode())+this.value_2.hashCode();
  }


}
