package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class PUSHENV extends Instruction {
  public final String illpushenv_;

  public PUSHENV(String p1) { illpushenv_ = p1; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Instruction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.PUSHENV) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.PUSHENV x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.PUSHENV)o;
      return this.illpushenv_.equals(x.illpushenv_);
    }
    return false;
  }

  public int hashCode() {
    return this.illpushenv_.hashCode();
  }


}
