package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class RET extends Instruction {
  public final String illret_;

  public RET(String p1) { illret_ = p1; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Instruction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.RET) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.RET x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.RET)o;
      return this.illret_.equals(x.illret_);
    }
    return false;
  }

  public int hashCode() {
    return this.illret_.hashCode();
  }


}
