package com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn; // Java Package generated by the BNF Converter.

public class SND extends Instruction {
  public final String illsnd_;

  public SND(String p1) { illsnd_ = p1; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.Instruction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.SND) {
      com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.SND x = (com.biosimilarity.seleKt.model.ill.vm.illvm.Absyn.SND)o;
      return this.illsnd_.equals(x.illsnd_);
    }
    return false;
  }

  public int hashCode() {
    return this.illsnd_.hashCode();
  }


}
