package com.biosimilarity.lift.lib.kvdbJSON;

import com.biosimilarity.lift.lib.kvdbJSON.Absyn.*;

/** BNFC-Generated All Visitor */
public interface AllVisitor<R,A> extends
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.Message.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.LblReqHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.LblRspHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.LblReqBody.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.LblRspBody.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.ReqHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.RspHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBRequest.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.KVDBResponse.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.AskReqPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.AskRspPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.TellReqPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.TellRspPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.ReqJust.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.RspJust.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.AskReq.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.TellReq.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.AskRsp.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.TellRsp.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.Status.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.Pattern.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.Blob.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.Substitution.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.SubstPair.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryTerm.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryElem.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryValue.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryArray.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryGrndLit.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryBool.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.QryNum.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URI.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URIPath.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URILocation.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URIRsrcLocation.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URIRelativePath.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URIRoot.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.NetLocation.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URIScheme.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.URIPathElement.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.DNSElement.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.Port.Visitor<R,A>,
  com.biosimilarity.lift.lib.kvdbJSON.Absyn.UUID.Visitor<R,A>
{}
