package com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expression implements java.io.Serializable {
  public abstract <R,A> R accept(Expression.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Application p, A arg);
    public R visit(com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Mention p, A arg);
    public R visit(com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Value p, A arg);
    public R visit(com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Continuation p, A arg);
    public R visit(com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Abstraction p, A arg);

  }

}
