package com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn; // Java Package generated by the BNF Converter.

public class Mention extends Expression {
  public final VariableExpr variableexpr_;

  public Mention(VariableExpr p1) { variableexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Mention) {
      com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Mention x = (com.biosimilarity.rlambdaDC.lang.rlambdaDC.Absyn.Mention)o;
      return this.variableexpr_.equals(x.variableexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.variableexpr_.hashCode();
  }


}
