package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Absurdity extends Logical {

  public Absurdity() { }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.Logical.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Absurdity) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
