package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Application extends LambdaExpr {
  public final LambdaExpr lambdaexpr_;
  public final ListLambdaExpr listlambdaexpr_;

  public Application(LambdaExpr p1, ListLambdaExpr p2) { lambdaexpr_ = p1; listlambdaexpr_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.LambdaExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Application) {
      com.biosimilarity.lift.lib.scalar.Absyn.Application x = (com.biosimilarity.lift.lib.scalar.Absyn.Application)o;
      return this.lambdaexpr_.equals(x.lambdaexpr_) && this.listlambdaexpr_.equals(x.listlambdaexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.lambdaexpr_.hashCode())+this.listlambdaexpr_.hashCode();
  }


}
