package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public abstract class Bool implements java.io.Serializable {
  public abstract <R,A> R accept(Bool.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.scalar.Absyn.Verity p, A arg);
    public R visit(com.biosimilarity.lift.lib.scalar.Absyn.Absurdity p, A arg);

  }

}
