package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Calculation extends Expression {
  public final ArithmeticExpr arithmeticexpr_;

  public Calculation(ArithmeticExpr p1) { arithmeticexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.Expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Calculation) {
      com.biosimilarity.lift.lib.scalar.Absyn.Calculation x = (com.biosimilarity.lift.lib.scalar.Absyn.Calculation)o;
      return this.arithmeticexpr_.equals(x.arithmeticexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.arithmeticexpr_.hashCode();
  }


}
