package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Embedding extends Expression {
  public final Program program_;

  public Embedding(Program p1) { program_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.Expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Embedding) {
      com.biosimilarity.lift.lib.scalar.Absyn.Embedding x = (com.biosimilarity.lift.lib.scalar.Absyn.Embedding)o;
      return this.program_.equals(x.program_);
    }
    return false;
  }

  public int hashCode() {
    return this.program_.hashCode();
  }


}
