package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Listed extends ValueExpr {
  public final ListExpression listexpression_;

  public Listed(ListExpression p1) { listexpression_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Listed) {
      com.biosimilarity.lift.lib.scalar.Absyn.Listed x = (com.biosimilarity.lift.lib.scalar.Absyn.Listed)o;
      return this.listexpression_.equals(x.listexpression_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpression_.hashCode();
  }


}
