package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Quantity extends ValueExpr {
  public final Numeric numeric_;

  public Quantity(Numeric p1) { numeric_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Quantity) {
      com.biosimilarity.lift.lib.scalar.Absyn.Quantity x = (com.biosimilarity.lift.lib.scalar.Absyn.Quantity)o;
      return this.numeric_.equals(x.numeric_);
    }
    return false;
  }

  public int hashCode() {
    return this.numeric_.hashCode();
  }


}
