package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Reduction extends ArithmeticExpr {
  public final Expression expression_;
  public final ListExpression listexpression_;

  public Reduction(Expression p1, ListExpression p2) { expression_ = p1; listexpression_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.ArithmeticExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Reduction) {
      com.biosimilarity.lift.lib.scalar.Absyn.Reduction x = (com.biosimilarity.lift.lib.scalar.Absyn.Reduction)o;
      return this.expression_.equals(x.expression_) && this.listexpression_.equals(x.listexpression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expression_.hashCode())+this.listexpression_.hashCode();
  }


}
