package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public class Utterance extends ValueExpr {
  public final String string_;

  public Utterance(String p1) { string_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.lib.scalar.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.scalar.Absyn.Utterance) {
      com.biosimilarity.lift.lib.scalar.Absyn.Utterance x = (com.biosimilarity.lift.lib.scalar.Absyn.Utterance)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
