package com.biosimilarity.lift.lib.scalar.Absyn; // Java Package generated by the BNF Converter.

public abstract class ValueExpr implements java.io.Serializable {
  public abstract <R,A> R accept(ValueExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.lib.scalar.Absyn.Listed p, A arg);
    public R visit(com.biosimilarity.lift.lib.scalar.Absyn.Quantity p, A arg);
    public R visit(com.biosimilarity.lift.lib.scalar.Absyn.Quality p, A arg);
    public R visit(com.biosimilarity.lift.lib.scalar.Absyn.Utterance p, A arg);

  }

}
