
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 10 00:00:47 PDT 2011
//----------------------------------------------------

package com.biosimilarity.seleKt.model.ill.vm.illvm;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IllDUP = 35;
  public static final int _SYMB_16 = 18;
  public static final int _SYMB_15 = 17;
  public static final int _SYMB_14 = 16;
  public static final int _SYMB_13 = 15;
  public static final int _SYMB_12 = 14;
  public static final int _SYMB_11 = 13;
  public static final int _SYMB_9 = 11;
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_10 = 12;
  public static final int _SYMB_7 = 9;
  public static final int IllREAD = 34;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int IllPUSHENV = 19;
  public static final int IllFST = 30;
  public static final int EOF = 0;
  public static final int IllPUSH = 23;
  public static final int IllUNUNIT = 27;
  public static final int IllUNIT = 26;
  public static final int error = 1;
  public static final int IllRET = 22;
  public static final int IllPOP = 24;
  public static final int IllHD = 20;
  public static final int IllTL = 21;
  public static final int IllSND = 31;
  public static final int IllINR = 33;
  public static final int IllINL = 32;
  public static final int IllAP = 25;
  public static final int IllUNPAIR = 29;
  public static final int IllPAIR = 28;
}

