package com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn; // Java Package generated by the BNF Converter.

public abstract class RLLRightPtrn implements java.io.Serializable {
  public abstract <R,A> R accept(RLLRightPtrn.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn.InRight p, A arg);

  }

}
