package com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn; // Java Package generated by the BNF Converter.

public class Selection extends RLLExpr {
  public final RLLExpr rllexpr_1, rllexpr_2, rllexpr_3;
  public final RLLLeftPtrn rllleftptrn_;
  public final RLLRightPtrn rllrightptrn_;

  public Selection(RLLExpr p1, RLLLeftPtrn p2, RLLExpr p3, RLLRightPtrn p4, RLLExpr p5) { rllexpr_1 = p1; rllleftptrn_ = p2; rllexpr_2 = p3; rllrightptrn_ = p4; rllexpr_3 = p5; }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn.RLLExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn.Selection) {
      com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn.Selection x = (com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn.Selection)o;
      return this.rllexpr_1.equals(x.rllexpr_1) && this.rllleftptrn_.equals(x.rllleftptrn_) && this.rllexpr_2.equals(x.rllexpr_2) && this.rllrightptrn_.equals(x.rllrightptrn_) && this.rllexpr_3.equals(x.rllexpr_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.rllexpr_1.hashCode())+this.rllleftptrn_.hashCode())+this.rllexpr_2.hashCode())+this.rllrightptrn_.hashCode())+this.rllexpr_3.hashCode();
  }


}
