package com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn; // Java Package generated by the BNF Converter.

public class UnitLiteral extends ValueExpr {

  public UnitLiteral() { }

  public <R,A> R accept(com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.seleKt.model.ill.lang.illtl.Absyn.UnitLiteral) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
