package com.biosimilarity.lift.lib.amqpJSONAPI2;

import com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.*;

/** BNFC-Generated All Visitor */
public interface AllVisitor<R,A> extends
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.Message.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.LblReqHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.LblRspHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.LblReqBody.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.LblRspBody.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.ReqHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.RspHeader.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.KVDBRequest.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.KVDBResponse.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.AskReqPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.AskRspPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.TellReqPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.TellRspPacket.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.ReqJust.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.RspJust.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.AskReq.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.TellReq.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.AskRsp.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.TellRsp.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.Status.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.Pattern.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.Blob.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.Substitution.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.SubstPair.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryTerm.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryElem.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryValue.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryArray.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryGrndLit.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryBool.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.QryNum.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URI.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URIPath.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URILocation.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URIRsrcLocation.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URIRelativePath.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URIRoot.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.NetLocation.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URIScheme.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.URIPathElement.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.DNSElement.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.Port.Visitor<R,A>,
  com.biosimilarity.lift.lib.amqpJSONAPI2.Absyn.UUID.Visitor<R,A>
{}
