package com.biosimilarity.lift.lib.term.Prolog.Absyn; // Java Package generated by the BNF Converter.

public class Complex extends Term {
  public final Atom atom_;
  public final ListTerm listterm_;

  public Complex(Atom p1, ListTerm p2) { atom_ = p1; listterm_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.term.Prolog.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.term.Prolog.Absyn.Complex) {
      com.biosimilarity.lift.lib.term.Prolog.Absyn.Complex x = (com.biosimilarity.lift.lib.term.Prolog.Absyn.Complex)o;
      return this.atom_.equals(x.atom_) && this.listterm_.equals(x.listterm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.atom_.hashCode())+this.listterm_.hashCode();
  }


}
