package com.biosimilarity.lift.lib.term.Prolog.Absyn; // Java Package generated by the BNF Converter.

public class ConsV extends Lyst {
  public final ListTerm listterm_;
  public final Var var_;

  public ConsV(ListTerm p1, Var p2) { listterm_ = p1; var_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.lib.term.Prolog.Absyn.Lyst.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.lib.term.Prolog.Absyn.ConsV) {
      com.biosimilarity.lift.lib.term.Prolog.Absyn.ConsV x = (com.biosimilarity.lift.lib.term.Prolog.Absyn.ConsV)o;
      return this.listterm_.equals(x.listterm_) && this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listterm_.hashCode())+this.var_.hashCode();
  }


}
